### ISSUE TITLE
New animation on button is longer than button itself

### ISSUE THREAD

**Issue by Angotic** [Angotic/ViSE-#3]
On the left side of the button we have animation that triggers while you hover it
<img width="813" alt="Снимок экрана 2019-06-17 в 21 58 38" src="https://user-images.githubusercontent.com/34067934/59629265-1ad12680-914b-11e9-81b8-621eada526c5.png">

**Comment by Angotic** [comment]
To better understand the problem and solution add some information please

**Comment by LizaVasina** [comment]
Fixed bug with changing position of the button animation, commit https://github.com/Angotic/ViSE-/commit/0e8cacd64a6d5d26c8342caa001afbb792b794ac
