### ISSUE TITLE
Colors changing 

### ISSUE THREAD

**Issue by Angotic** [Angotic/ViSE-#4]
When hovering the red buttons, the color changes to the dark blue. It will be better if it will change to the dark red one
<img width="288" alt="Снимок экрана 2019-06-17 в 22 02 40" src="https://user-images.githubusercontent.com/34067934/59629515-b2cf1000-914b-11e9-863b-143e47313574.png">

**Comment by Angotic** [comment]
Please add some information about the solution before closing the issue

**Comment by LizaVasina** [comment]
Added new color to all run buttons, now it`s dark red #b22c32
commit https://github.com/Angotic/ViSE-/commit/0e8cacd64a6d5d26c8342caa001afbb792b794ac
