### ISSUE TITLE
New status bar and animation for it

### ISSUE THREAD

**Issue by Angotic** [Angotic/ViSE-#5]
Create a brand new status bar and animation
<img width="1423" alt="Снимок экрана 2019-06-17 в 22 05 45" src="https://user-images.githubusercontent.com/34067934/59629686-122d2000-914c-11e9-99e1-fe8fe4726a72.png">

**Comment by LizaVasina** [comment]
Created new animation for status bar, commit https://github.com/Angotic/ViSE-/commit/f0aedb6c09563018e0dd11531cbd99721ab40a4f
